import type {ReactNode} from 'react';
import type {Metadata} from 'next';
import { Inter } from 'next/font/google';

import NavBar from '@/app/NavBar';

import './globals.css';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout(props: { children: ReactNode }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <NavBar />
                {props.children}
            </body>
        </html>
    )
}
