import type {ReactNode} from 'react';
import type {Metadata} from 'next';
import { Inter } from 'next/font/google';

import NavBar from '@/app/NavBar';
import Equalizer from '@/app/Equalizer';

import './globals.css';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout(props: { children: ReactNode }) {
    return (
        <html lang="en" className="h-full">
            <body
                className="bg-gradient-to-b from-background from-25% to-theme bg-fixed text-white h-full"
                style={inter.style}
            >
                <NavBar />
                {props.children}
                <Equalizer />
            </body>
        </html>
    )
}
